cerberus: add smbus filtering support
The patch adds smbus filgering feature for cerberus solution as cerberus doesn't support
smbus filtering configuration

Environment Step:
AST2600 i2c4 is connect to PFR SMB-Filter-3-in on AST2600 DCSCM2.0 Dev Kit.
We need to connect an i2c device to PFR SMB-Filter-3-out, then pfr can
monitor i2c commands between i2c4 and i2c device.
 - Connect J25 pin 7 to J26 pin 8  (PFR SMB-Filter-3-out -> AST2600 i2c8 SCL)
 - Connect J25 pin 9 to J26 pin 10 (PFR SMB-Filter-3-out -> AST2600 i2c8 SDA)

AST2600 debug console:
 - Create slave mqueue on i2c8
    root@ast2600-dcscm-amd:~# echo slave-mqueue 0x6c > /sys/bus/i2c/devices/i2c-8/new_device
    [  140.232513] i2c i2c-8: new_device: Instantiated device slave-mqueue at 0x6c

    root@ast2600-dcscm-amd:~# i2cdetect -y 4
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    60: -- -- -- -- -- -- -- -- -- -- -- -- 6c -- --

 - Send i2c command to i2c8 device 0x6c
    root@ast2600-dcscm-amd:~# i2c-test -m /dev/i2c-8 -s /sys/bus/i2c/devices/i2c-8/8-006c/slave-mqueue -a 0x6c &
    root@ast2600-dcscm-amd:~# i2cset -y 4 0x6c 3 1
    [1131.654818154] : d8 03 01
    root@ast2600-dcscm-amd:~# i2cset -y 4 0x6c 5 1
    [1134.264368107] : d8 05
    Error: Write failed

AST1060 debug console:
 - Check AST1060 console, command 0x05 is not in the whitelist.
    [00:00:10.316,000] <inf> pfr: SMBus Rule Bus[2] RuleId[1] DeviceAddr[d8]
    [00:00:10.316,000] <inf> pfr: ast_i2c_filter_en ret=0
    [00:00:10.316,000] <inf> pfr: ast_i2c_filter_update ret=0
    [00:00:10.316,000] <inf> pfr: Whitelist
                                  1f fe 89 38 2f 00 ef 3f  00 00 00 00 00 00 00 00 |...8/..? ........
                                  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........

Signed-off-by: Steven Lee <steven_lee@aspeedtech.com>
Change-Id: I70c118d7df02cc0d736d49f957ae3429d635f780